### get movies

http://localhost:3000/movies


### get movies by id
http://localhost:3000/movies/c906673b-3948-4402-ac7f-73ac3a9e3105


### get movie by genre
GET http://localhost:3000/movies?genre=action


### post movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "rate": 5,
  "genre": [
    "Crime",
    "Drama"
  ]
}

